# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название рекламы')),
                ('number_of_impressions', models.IntegerField(default=0, verbose_name='Количество показов')),
                ('file', models.FileField(help_text='Видео в формате .ogg| .ogv. Изображения в формате .png .jpeg', upload_to='', verbose_name='Файл с рекламой')),
                ('orientation', models.CharField(choices=[('Vertical', 'Вертикальный'), ('Horizontal', 'Горизонтальный')], default='', max_length=30, verbose_name='Ореинтация баннера')),
                ('active', models.BooleanField(default=False, verbose_name='Показ на экране')),
                ('type', models.CharField(choices=[('Video', 'Видео'), ('Image', 'Изображение')], max_length=30, verbose_name='Тип')),
                ('time', models.IntegerField(default=0, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('start_date', models.DateField(default='', verbose_name='Дата начала')),
                ('end_date', models.DateField(default='', verbose_name='Дата окончания')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/event', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='PlayListAdvertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Плэй лист рекламы',
                'verbose_name_plural': 'Плэй листы рекламы',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=400, verbose_name='Имя')),
                ('phone', models.CharField(default='', max_length=250, verbose_name='Телефон')),
                ('work_time', models.CharField(default='', max_length=250, verbose_name='Рабочее время')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, max_length=300, upload_to='media/shops', verbose_name='Изображение')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', help_text='В случае отсутвия адресса, введите название объекта', max_length=300, verbose_name='Адресс')),
                ('index', models.CharField(default='', max_length=300, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('location', models.CharField(help_text='Серийный номер терминала', max_length=300, verbose_name='Позиция на карте')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='api.Structures', verbose_name='Адресс магазина'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='play_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='api.PlayListAdvertisements', verbose_name='Плэй лист рекламы'),
        ),
    ]
